### ISSUE TITLE
Problems with react navigation and relay

### ISSUE THREAD

**Issue by jean-leonco** [jean-leonco/Foton-mobile#1]
The App connect with the API and fetch products, but the Dashboard page does not have access to data.

**Comment by jgcmarins** [comment]
why?
could be related to data mask
could share piece of code or link?

how is the result from the query?

**Comment by jean-leonco** [comment]
Here is the root query of App when authenticated: 
```js
const isAuth = true;

  const Routes = createRouter(isAuth);

  if (isAuth) {
    const Root = () => {
      const query = useQuery(graphql`
        query AppQuery {
          ...Dashboard_products
        }
      `);

      return <Routes />;
    };

    const RootWrapper = () => {
      return (
        //@ts-ignore
        <ErrorBoundaryWithRetry
          fallback={error => <ErrorScreen error={error.message} />}
        >
          <React.Suspense fallback={<LoadingScreen />}>
            <Root />
          </React.Suspense>
        </ErrorBoundaryWithRetry>
      );
    };

    return <RootWrapper />; 
```

Relay finds the fragment and send requisition to server. 
![image](https://user-images.githubusercontent.com/48924243/66857822-70cda380-ef5e-11e9-9550-91ffc0506c4f.png)

But the const that receive  useFragment, products appears as null.

```js
const products = useFragment(
    graphql`
      fragment Dashboard_products on Query {
        products(first: 10) @connection(key: "Dashboard_products") {
          edges {
            node {
              id
              name
              description
            }
          }
          pageInfo {
            hasNextPage
            startCursor
          }
        }
      }
    `,
    props.products,
  );
```

**Comment by jgcmarins** [comment]
try to copy the curl from network tabe
and test it through terminal
if there is no data, the problem is on backend
if there is data, the problem is on client

**Comment by jean-leonco** [comment]
The problem seems to be on client. Using the curl on terminal, the information was returned.

![image](https://user-images.githubusercontent.com/48924243/66866913-a9767880-ef70-11e9-8b28-4a633e4a24fa.png)

The problem has to do with client, probably in the way that information is provided to children

**Comment by jgcmarins** [comment]
nice
how can we debug it on client?
which methods of relay-experimental are you using?
do you have any link to the code where this problem is happening?

**Comment by jean-leonco** [comment]
I am using `useQuery`. In the [relay-examples-hooks repo](https://github.com/sibelius/relay-examples-hooks/tree/feat/hooks), I saw the `UseLazyLoadingQuery`, but it didn't come with relay-experimental. Could that be the issue?
The parts of the code where this problem is coming from are [`use Fragment`](https://github.com/jean-leonco/Foton-mobile/blob/feat/RELAY/src/modules/Main/Dashboard/DashboardList.tsx#L76) and [`UseQuery`](https://github.com/jean-leonco/Foton-mobile/blob/feat/RELAY/src/modules/Main/Dashboard/DashboardRoot.tsx#L32).
I think the best way to debug is focusing on the useFragment hook. Sometimes that [warning](https://github.com/facebook/relay/blob/ba9935653c16e85ef8880cefda1f59de6b8f3c88/packages/relay-experimental/useStaticFragmentNodeWarning.js#L32) shows and sometimes it doesn't show.

**Comment by jgcmarins** [comment]
the problem is data masking:
data asked by the [fragment](https://github.com/jean-leonco/Foton-mobile/blob/feat/RELAY/src/modules/Main/Dashboard/DashboardList.tsx#L76) won't be available on it's [parent](https://github.com/jean-leonco/Foton-mobile/blob/feat/RELAY/src/modules/Main/Dashboard/DashboardRoot.tsx#L32)

this is a relay feature

components have access to the data they ask for and that's it

**Comment by jean-leonco** [comment]
But how could we have access to data? Since [here](https://github.com/jean-leonco/Foton-mobile/blob/feat/RELAY/src/modules/Main/Dashboard/DashboardRoot.tsx#L47) the root component won't have the information.

**Comment by jgcmarins** [comment]
[colocation](https://github.com/sibelius/react-colocation)
each component ask for the data they will use
a component should not ask for data that won't be used
